# Generated by Django 3.1.7 on 2021-04-03 22:18

import dcim.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asnPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('first_asn', dcim.fields.ASNField()),
                ('last_asn', dcim.fields.ASNField()),
                ('tag', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('pool_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='blueprintModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('blueprintId', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ipPoolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('subnet', models.CharField(max_length=50)),
                ('tag', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('pool_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='securityZonesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('securityZoneId', models.CharField(max_length=150)),
                ('securityZoneRouteTarget', models.CharField(max_length=100)),
                ('securityZoneType', models.CharField(max_length=100)),
                ('securityZoneLinkedBlueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aisPlugin.blueprintmodel')),
            ],
        ),
        migrations.CreateModel(
            name='vniPoolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('first_vni', models.PositiveIntegerField()),
                ('last_vni', models.PositiveIntegerField()),
                ('tag', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('pool_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='virtualNetworksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('virtualNetworkId', models.CharField(max_length=150)),
                ('virtualNetworkIp', models.CharField(max_length=150)),
                ('virtualNetworkOverlayType', models.CharField(max_length=150)),
                ('virtualNetworkLinkedSecurityZone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aisPlugin.securityzonesmodel')),
            ],
        ),
    ]
